dict = {'UUU' :  'F',
        'CUU' :  'L',
        'AUU': 'I',
        'GUU': 'V',
        'UUC' :  'F',
        'CUC' :  'L',
        'AUC' :  'I',
        'GUC' : 'V',
        'UUA' : 'L',
        'CUA' : 'L',
        'AUA' : 'I',
        'GUA' : 'V',
        'UUG' : 'L',
        'CUG' : 'L',
        'AUG' : 'M',
        'GUG' : 'V',
        'UCU' : 'S',
        'CCU' : 'P',
        'ACU' : 'T',
        'GCU' : 'A',
        'UCC' : 'S',
        'CCC' : 'P',
        'ACC' : 'T',
        'GCC' : 'A',
        'UCA' : 'S',
        'CCA': 'P',
        'ACA' : 'T',
        'GCA' : 'A',
        'UCG' : 'S',
        'CCG' : 'P',
        'ACG' : 'T',
        'GCG' : 'A',
        'UAU' : 'Y',
        'CAU':  'H',
        'AAU' : 'N',
        'GAU' : 'D',
        'UAC':  'Y',
        'CAC':  'H',
        'AAC':  'N',
        'GAC':  'D',
        'UAA':  'Stop',
        'CAA':  'Q',
        'AAA':  'K',
        'GAA':  'E',
        'UAG':  'Stop',
        'CAG':  'Q',
        'AAG':  'K',
        'GAG':  'E',
        'UGU':  'C',
        'CGU':  'R',
        'AGU':  'S',
        'GGU':  'G',
        'UGC':  'C',
        'CGC':  'R',
        'AGC':  'S',
        'GGC':  'G',
        'UGA':  'Stop',
        'CGA':  'R',
        'AGA':  'R',
        'GGA':  'G',
        'UGG':  'W',
        'CGG':  'R',
        'AGG':  'R',
        'GGG':  'G'}
count = 1
sampList = []
protList = []
string = 'AUGAAAGAUUACCGGCCGGUUGAUCUCUGUCGGUACUGGUACCCGAAGCUCAACUUAAUUUCGGGCAUCCCGUGUGUGCCCGGGCCUCGCCGCCUAGAAAGGAACAGACUCGGUUGCGCACCAUCCGUAACAUACCGUAACAUGGCAGAAUUAAAAGUUAGCAUCCGUGCAGCAGUGUGUAUAUGGAGACAUGGGCAGAGCCAAAAAGAGACUAAACGGGCCUACCAGUUUGUGCCAAGAUUAUGGUUAUCCGUUGUCAUCCACACGCCGGGUAAUAUCCCCAAUGUCUCUUUGGGGAUACCUUCGGCGCGGUACCAAGGCGACGCACGUAAGCGGCGCCGAUGUACCAAGACGCGCAUGCCCGCAGAUCAGGCGAGGACACAAAGGGUUAACUACUUUGGGAGGGAACGGUUUUCUUCGUGGUGGCUGUACUUCUAUAGAGUAUACGGUGAAAGCUGCUCCUUCCCUAAGUUUUUUAUACGUGGACUUCUAGAGGUGGGAAUAAAGUAUGGCUUCGUUGUGGAACGCCCGCGCCGACUAUUAAGUAAGUGCAAUUCGCCUUACUGUGAUAGCCCAUACUUAGCUUGUGGGGAAGUGCUCAGGCUCUCUGGAAUGCAAAAAUCUCGUGGUCUCACCUCACAGUAUCCUGCAAAUACGGACCGCUCUUACGCGCGUCUCGGCAAGUGCCACUCACCCCGACCAAACGAUAGCCCACUAGUACAGGCAAUGCCCAACCUUUGUCCCAGGCCGCCCCCAUUGCAGCCCCACCUCGGACGACUAAGACGGCGAGGCCACAUGAUUGCUCCCAUUCGUAUUACUCUCGUGAUUGCCUCAAAGUCAACGAUAAGAUCCAAGCAAAUGGUCUACGGUGUAGACGGAUCCAGCAAGCACAUGGUUGUACAAGCAGCCUUAGCCCGCGACGACAAAUCUUGGCCCCUUACGCUGGAGACGCUUGUCCUUCCUAGUCACGGCAACCACCUGAUCACUGCCUGGAAUUGCAAUCGUCGGUGGUACGAUUACCUGUCAUUUGCCCCACGGGCAGGAGUAUGCACAAGGGUUUUGCAACAUAGCGCAAAAACGCAAGUCCGCGCGGGCAUAAUAGUUGAUGCAGCUAGGCGGGUGCGUACCCGGUCUAUUCAUACUCGCUGGCCAGGAGAUAAGUGUGUCAUCAGUGCUUGUUGUAGAGGCACAUGUCGCCGCCGUAGCCUCCACUCUGCUGUCGCCACAGGCGCCCGCACACGAGCAGAUCAAAAUCUGACGGGUAUUGGAAGGGUUCAAUCUGUUAAUUCAGCAGGACCUCGUCUCCGAAUGGACAUUUCCUCCGGGAGAUGUGUCGUUACAAGAGAUGAAACUCCCGCAUACCGGCGGUUCCGAAACAGUCACAACAGGCCCGUACACAGACAGCGACAGCGUGCGCGCGCAUAUAGAAAUCACUUUCACGAAUUCCAAGCUAACACAUCCAAACGUAUCUACGUAGACCGUCAAAUGUGUUACUCGACCCGACACAAGCAUAAUAUACAGCGCCAUACCCUUUUACCACGCUAUUGCCCUCCUUCGGGAAGGUCCAGCUCAGAAAACGGGUUCGUUGAGAAGCAAAGCGAUGGCAAGACCUUAAUUACGUCACCGCUUUGUGCUCAAAAUCUAUACUCUGGUGCUAUUAAUUUGUGCCGGUCCGGGGCGCCUCUGCAUGGGUGUCGGGGGGUCAACGGCAGGCCACACCGUAACAAGCGCGCGGCUAGGUCCCUACGGAAAGGACGCUUAGUAGGUCUCAUGACCGGACUUGGCCUCAUUGCACACUUGCGGUCCAACUCCUCUCCGACUACGACAACUUUAACUCGAGGCAACCCUAAGGACCCAGGAGCGAGGCCGGAGCUUCUGAGGCGCGGACACACAACCCGCUCCAUUUUGAUUGACACCUUCGCUUGUAAGAACCCGGGCGUCAAUCGUACCACCUUCGGGGCCCUUGAUACAGACAUGGAUCUGUGCGAGGUCGGUGUUGCGACAAUGGAAUUUGUAGCUUCGCGCACUAUGGGUCGUAUCAGAGCGGCUGUCUUUGCAAUGGGGCCGCGAGUGCAAGUGCGUCGAUCCCUACGCAUGCCUUUCCAGAGGGCUGUACACCUGAUGGACACUGAAACGCCACGUCGCGGAUUGUACGUAGACAGUUCUCCUUCAAUAGCCUACCCGGCAACAUAUGGGAGUACUCCGCCUCCAUCCCGAGAUGUCGCAAUUUGCGUCUAUUCGAGGAAUAACCCUAACCGAUAUGGCAAACCACUCCAUGGUUCCCGCAACGAAGUGGCCGCGAGAUCGCGCACUAAUGCGAUUGUACGGGCACCCAACUGCUGCGAGAAUAUUUAUAAAAUAUGCGUGGGCUUAACGGCGACGCAAUCGAACCUUCUAACAAAAUCAGAAGUUUUACUCGGUGAUGUUAAGGCCAAUCCACUAGCCAUUCGAACAACGCAGGGUUUUUGCAUGCACAUGUGCACGCGCAUCUUGCCUGAGAGUGGUGCCGCGCAGUAUCGCGCGCACUCACAGUCUGGACAGCGGAAUAUAUCAUUACGAGUCCUACUACUCUUCUAUCAGUGCUUAAAUCUCUCUAACCAAUCGCCCCUACGAACAUUAAAAACUGCUGGACAGUAUGGCUCAGCCAAAUGUGGCGAAAAACACGCCUCGUCACCACAGUGUCUUUGCGUAUUGCAGCAGAGGGUAGACCCCAGAGCAUACUAUUCAAAUGGUGAUUUACCUCGUUGGCCUGUCAUCAAAAUAAGUUUGAACGCACCUCACACCUAUAACCCGAAAUGCAGAUAUUGUUACUCUCCGGACUUACUUCUGCAUCCUGUGGCGUGCCCCAAUAAUACAUACAUUGCGGUAGAUCAGGUCGGAACACCCAGACAGGAGGUCCCUGACACAACCACCACACUGCAUCGCGGUCCCGAACAGGCGGAUGCACACAAAAUCUGGGUCCGACGCCUUUUCGUACCUAGUUAUAAAAUUAUGACUUCUUAUGUUCGUAGCCCGUGGUCUGUCGCUUUGCUUUCGCAUGAAGGGUUGAUGAUAUGUGGAUCUAAGUGGCAAAACUCGGUGUCGCCUCGAGAGGAUAGAUGGACGUGUGACAUCGAGGGUACACUGCGCUUUGCGAUAGGACGCUUGAACCUCGGCCGCCUCAUUCUUAAACCAAUCGUUUCUAGACUCCGACGUUCUAGGCUGACGGGCGGUACGCCCUUGCACACUGAGAGGAGUUCAGGACGGUGCGCCGUCACCUCGGAGUUAACUCCACUUGGGCACAUAGCACCUCUGCUCGGUUGUGCACUAAAACAAAUCACUCUGGUUGGGAAAGAAGCUCGGCUAAACACCCCAUCCCUAAUGCAGAUUGCACUGCAUGGUCGUUACAAGAGCUUUGUGGCCGGUUCGCGCGCAGCUGGCCCUGCCGUCUGCAGACUGGGGUGCAUCGGGCUCCCAAACAGUCGGAACAAAAUCACAUACGGACACCGUGCGGAACCAGCCACAACGAGGACCAGUUCCCUGACAGCUGGUGCCCGAGGGCAGAACCUUGCGGGAGAUCGAAUUCUUGACUCUAAAUAUCACAGAUUGAUAAGCUUGUAUCAGUUUAGCCGAUUUGCAAGGCGUGCCAUCGUACUCCGGCAGAGUUUCGAGUUCAGAGAACUGGGCGUCGUCCCAUGGCUACUGACUGAGGCAGAUCUGAGAACAAACGAAUCGGUAAGGGCAGUGUUGGUGGUAACAUUCUCGUGCUUCAUGGGUUCCGUCUUCGCUCACAUAUUAACCAUAUUGCUUUGCGGAUGCACUACGGCAGCGCCCCUCCAGGGAAGACAAUGCCAAGUGAGCGCGACGCUGUUAGUUGUUUGCUUUGGGCUACAUUUGUCGCAGAACCUAGGAUAUAGUACAGCAGCACUAUUGGUAGGGUUGUCGCACCUAAGGAAACGUGGACGCCAACGGUUGACUCCUGAAACUUGGGCAAUUAACUUGGGUAAAGCCAGGGUACCACCCCUAUUGUUGAUGGUCACGACGCUCCCGGCCGUUUUCUCAAUAGUCUCUACGGCAGUUCGCGGAACUUGCUCGCCCGCCUUCUGUCUCAAGGUUCGGCAGCACGCCCCUCUAGUAAUUAAUCUAGGUGUUGUACCCCUAGGCGCACAUCGAAAACGCUCGCCCCUAUUCUUUUCCCGCUAUCAUACCUCUACUCGCGCAGAGCGCCGCCACUUUAUAGUCUCACGGUCGUACCGGGAACAACCACUGAAAUUGAGAUCUCUAUCUGACAGGUCGAUUGCACGAAACCACAAACCACGGGAUCUUCCGGGAGCUGGAGAGUCUAUUGUAAUACCGGGGGAUCAUAGUUACAUAGGAGGUUGGUGUCGGUGUUCGUCAUACGAUCAUGGCCAUACGCGUCCAGCAAUCAUAGAUGGCGUACUUGGGCAUUCCUCGUUCAUAUCCCGCAGCACUGAAAUCUUAAUUGGGUUCUCUGGUGCUAGCCGAAACUCACAGCCUGUGUACAGUGCCGGACCACGAGCGGCCAGUCCGAAACGUCGCUGGCCAGAGUCGUGGCCUACCAUAAUAACGAUACAGUCCCCUAAGAUUGGAUACCCGCGUAAGAACCAUCGUCUGGGUAAAAAUCGAAUCCUCGGAGUAUGCCUGGUUCGGCUGACUCCUGACCCCUUAGUUGGGUCGUCGGUACUCACUAGGCUGCCAUGUGCAAUUUGCCAUUGGAUAUGUCGGUCAACGCACCGGGAUCAUAUGUGCCCUACGUGUGCGCUUGGCUUUUUAAUCUAUCGGUACACAAAGUACCGCUACCAAUGCGCGCAACGAAACCAAACACUAGGAAUCAUGACUCAUGCCAUACCACUUCUUCCUCAACUACACUUUCGCCUAACGUACUCAGUGAUUAGGAUCUCCACCUCGCUAUCAAGUAUGGUAAAUGGUGGAUUAGUCGGGGGGUGCUUCGCCACUUAUUCCUAUAGAUCAAGCCCGUCUCAGGUAGCCCCUAUCGCUCCUCCGGUAUCGUCUCCCAAAGCUAAAUUUUAUAUGGACGAUACCCAACUGAGGAUUCUUAAGAGGUCGGUCCAAUCUUGGGGCAGUUUGCAGUGGCAGCGCCAAUUAAAUUUUUUACAUGAGGCUUCAUUGCCAAAGCGAAUGGUGCGAAUGCUGUUUUGGCCAGAACCCUCUUCAAAGGGAUCGCGGUGUGAGAGCCUCAAUAUUGUUCAAUUUUUUUCCAUUGUCUAUUGCAUGUCUCAGUCGAUGCGCAGGAGAGCAGGAUGUCCACACGCCUCUUGCCGUGCUCCCCGCAUCACGAUCGACGUUGCAGCUGUUAUUCCUAACUCUGUGCACUCUAUAGUGAGGUUAGCCAAGCUUUACCUAAGGGGGCAUUGUGGAUAUAUAGGUACCCUCGCCUAUAUCUGCUCCGAGUCAUCGUCCGGGUGUGACGAAGCAUUCUCAUGUGGGAAGAGGAUUCGGUACUAUAACUUAGGUGCAAAUGCAUGGUCAAUGCAAUUAUCAACAAUCAGAGGGGUUACGCGUAUUUCAAAUAUUUGCAGAUCCCCGUUUUGCUAUCGGAGAGUUCCCGCACUAGGCUCGCGGUGGCUCAUAAGUGCGCACAUUCUCCGUGGCUUCUUGAUUGUUCAAGGGAUAGGAUCAGAUGCAAUAGCACAAAAGCCCGAACACCAACUGGGCGUGCAUCGAAACAGUGUUUGGUCCUGGACUCUUUACGGUACUGGCACCGUGGGGGCGGCGGUUUCACCAUCGGAUACCAAAGCGGAGAAUCGCCGGCAAAGAUUGCAUGCGGGCAAAUGCCCAUCCUCUACUCUGUUCGGACCCCUAAUCGAAACAUCUCAUCUUCCAAAGGUAAACCAUUCACGUACAAGUGACAGCAUGACCCGUGAGAAAGUGGAGGAUAAAAUUCACCCCACAUGUAAGGAUACUCGGCAGCUCUGCCCGCGUUUCCACACCGCUUCCCAUGGCGAUAUUGCCCCCAACGACAAUGGUGCUACUCCUAGGUGGAACAAACUUGGGUCCUCGACCCCGAAUCCUCAGAGCGGCCUUUGUCAAUGCUCUGACUACCACUCAAAUACGGAGUCCCCAUCUUUCCGAGGGACAUUACUCCUAGAACUUCAAAGAGACAUGUAUAGCUUCUAUGCGUUGCGUCAAUUAAAGUCAAGCAUCCGCACUACUCACAGGCGGCUGCGCUGGUGGAUCCACUUGGAACGGUUUUGCCUCGUCACGUUCCCGAAUACUUUUUUAUUGGUCAGAUCAGUCAUGCCCGGACCGCUGAUAACUAUAAGUCCUAGGCUGGUUUUAUCUAGCGAAGAACCCCCUUGGCUGAAAGUUGUUCGUUUUAAGGAGUCUCCCUGCAUGAGCGAGAGAAGGAUUGCGGCGCGGGCCAUCCUUCAGAGAGCACAUGACUGUCAAGCGCAUAAAGAGUACUUGCCCCACCGUCGUACGAGUACGCUUAAGCAAAAUGGGGCCACCGUCAACGGGCCUUACAUAAGAAGAGAUAUAUCCACGCGCCAAUGGGGAAAGCGCGUAGGGAGGAACCCCUGGGGAACUAUGACACAUGGCCCGCACCCCCUGGAGGGGCUCGGGCCACGGAUUGUUUUCCCAGUCCGCUUUCAGUUGAGCAUAGAACUUUCGUUUUACGGUUUCACAUCGGUAGUCAGCCGAAAGAUGGUUAUGCUGAGGUCAUCCCACAAGAUUGUUGUGAGGGGCUGCUUGCCUAGAGCACUCAAGUCGAAUGACUAUAUUACGCCUGUCAAAUUCGCAGCCCGUUGUCCCAGCCGCUGGCUAAUAGGCGCGCGUGUGCAUGGUGUCAAUGCCAGUUGCUGGCGUAGACGAGAAAUAAUGUCGCCCCCGUUAGGGACACUCGGUCUAAAGCGGAGUGCAUUCCGGCUGGUUGUUAUAAAUACCCUUUUAGCUGGGGCCCUGAGAGCGUUUGAGUCGCUGUCAGUUUUCAGGCUAUUUUUUUCUGCCUCAGGCGCUAAAUUAACCGUCCUCCCGACUGUGGCGUAUUGGGUGCAUACCUUUUCCUGUCGGGAACAACUAGAAAUAGUGACGGAUAUUCACUGGCUACCACGUGACGAUGUUUUUGGCAUGAUGAUAGUCUUAGUCUAUCUCUCGGUAGGGGUACAUAAUCGUGUAACCGUGGCGCCGGGCUUUGUUCGUAUUCUUCCACAAGGAGAUGCUGCUCCUGCAAACAGUAGCAUGAAGUCAACAUGUAGGGGGCGGGUGUUUCCACGGGCAUUAGCAGCUUCUGGUUGCGAGCGUCCAAUCCUUCUAAGCCACGAAAGUAUAGGUAUUGGCCAACUGCAUCCUAAGGUUUCGAUAAGUGGCCGGUACCAAAUUAAUCUGAUCAGCUCAGAUCACGUAUCUUUCCCGGAACAUGGGCUCUCAGCAACGAGCCUAGACCCACUAACUCACGAACAGAAGGUGUAUUGCCGUCGGCAUGAAUGUUCGUGUCUCCAGUCGUCCACACCAAACUACUCAGUCCUAGUCAGGAAUGAGGAGGAAGAACUCCUCAGUACGCUCAAGAAACCGUGCUGGAAACUGUGUCAUAGGAUGGCGGGCGAUGAGCCCGAAAGUAGACGAACUCUGCUGUGGCAGCGGCUAUGUACAGCUGUAAUGGAUCAAUGUUGGCACAUAUACCGCAAAUGUACAAUCGUAACCAUUUAUAGACUGUCGACUGACAUGACCGUGGGCCUCUGUAGUGGGUCGGAUUCAGUCAGUCGGGAGCCGGAUUUCGAUGUCACCUCUAAGUGCGAGGCCCCCUAUCCUGCUGUGACUGGGGCAAAUUUCCACAAACAUUGCAGCCUCUUAGUUCCGAUCCCUACUACACACACGACGUGUUCCCUGUUAGAUGCGGGUUCGCGCAACGCCGAUCAGAAUCCCCAGAUGGCGUUCGGGCUGCUAAUAAAAGGAGCCCGUUGUAUUAUGUCGAGUUCCAUCGACGUUUCGCGGGUUCAGCAACGUCCGAGACUCCUAGAUAGCUUAAUGGGGGGCAGAUCCCCAGGGGGAAUAUAUUAUAAAUACCCUAUAAUGAGGGUCUGA'

for f in string:
        if count == 1:
                sampList.append(f)
                count +=1
        elif count == 2:
                sampList.append(f)
                count += 1
        elif count == 3:
                sampList.append(f)
                protList.append(dict[''.join(sampList)])
                sampList = []
                count = 1
print(''.join(protList))


